mode : "train"

species_list : [0,1,3]
month : 5
percent: True

data:
  files: 
    base: /home/mila/t/tengmeli/ecosystem-embedding/data/
    train: sample.json     
    val: sample.json
      

  loaders:
    batch_size: 6
    num_workers: 6
  normalization: None
  transforms: None