save_preds: True
save_path: "/network/scratch/t/tengmeli/ckpt/not_songbirds_bias_init"
load_ckpt_path: "/network/scratch/t/tengmeli/ckpt/not_songbirds_bias_init/epoch=14-step=14429.ckpt"
log_comet: False

comet:
  project_name: "env_ecosystem" #"ecosystem-duck"
  tags: ["test_run"]

save_preds_path: "/network/scratch/t/tengmeli/test_runs/trial/"
experiment:
  task: "ebird_classifier"
  name: "ebird_classifier"
  seed: 42

data:
  files:
    base: ""
    train: "/network/scratch/t/tengmeli/scratch/ecosystem-embedding/training/train_june_vf.csv"
    val: "/network/scratch/t/tengmeli/scratch/ecosystem-embedding/training/val_june_vf.csv"
    test: "/network/projects/_groups/ecosystem-embeddings/data/eval/eval.csv" 