save_path: "/network/scratch/t/tengmeli/ckpt/not_songbirds_bias_init_loc"
load_ckpt_path: "" #/network/scratch/t/tengmeli/ckpt/not_songbirds_bias_init/epoch=14-step=14429.ckpt"
log_comet: true

loc:
  use: true
  concat: false
  
comet:
  project_name: "env_ecosystem" #"ecosystem-duck"
  tags: ["not_songbirds", "no_env", "bias_init", "sgd",  "steplr", "resnet18", loc]
experiment:
  task: "ebird_classifier"
  name: "ebird_classifier"
  seed: 42

  module:
    model: "resnet18"
    pretrained: False
    init_bias: "means"
    means_path: "/network/scratch/t/tengmeli/scratch/ecosystem-embedding/training/means.npy"
    lr: 0.001

optimizer: "SGD"  #"Adam"
scheduler: 
  name: "StepLR" #"ReduceLROnPlateau" #"ReduceLROnPlateau" #or "StepLR" "WarmUp"
  reduce_lr_plateau: 
    factor: 0.1
    lr_schedule_patience: 5
  step_lr:
    step_size: 10 
    gamma: 0.5
  warmup:
    warmup_epochs: 10
    max_epochs: 100
  
  cyclical:
    warmup_epochs: 10

variables: &default_vars
    ped_means: &ped_means [2230.56361696, 1374.68551614,   20.45478794,   19.04921312,
         31.1196319 ,   61.24246466,   36.68711656,   44.25620165]
    ped_std: &ped_std [2355.3843699 ,  107.88685009,    8.71958154,    6.69679905,
         23.66400261,    8.79233844,    9.91992735,   13.1028541 ]
    bioclim_means: &bioclim_means [ 11.99430391,  12.16226584,  36.94248176, 805.72045945,
        29.4489089 ,  -4.56172133,  34.01063026,  15.81641269,
         7.80845219,  21.77499491,   1.93990004, 902.9704986 ,
       114.61111788,  42.0276728 ,  37.11493781, 315.34206997,
       145.09703767, 231.19724491, 220.06619529]
    bioclim_std: &bioclim_std [  4.62661648,   2.31306195,   8.73155144, 220.15217856,
         3.66556263,   6.94077974,   6.73345032,   7.90953848,
        10.58786476, 3.71622992,   6.67059767, 372.85954139,
        49.59671974,  28.9984291 ,  25.76078507, 138.92188873,
        93.54401194, 130.66050149, 143.05699293]
        
data:
  loaders:
    num_workers: 4
    batch_size: 8
  #What kind of satellite input ? "refl" for "raw" reflectance values or "img" for 0-255 values (only supported for "rgb" and "nir" bands)
  datatype: "refl" 
  
  bands: ["r", "g", "b", "nir"]
  res: 10 
  
  env: [] #["ped", "bioclim"] #"all" "ped" or "bioclim"
  ped: 
      #pedological rasters
      res: 250
  bioclim: 
      #bioclim 
      res: 1000
  
  files:
    base: "/network/scratch/t/tengmeli/scratch/ecosystem-embedding/training/"
    train: "train_june_vf.csv"
    val: "val_june_vf.csv"
    test: "test_june_vf.csv"
    
  target:
    type: "probs"  #binary or probs
    # choose subset of birds : "ducks" for trying on species [37] or "songbirds" (307 species) or None (full set 684 species) "not_songbirds"
    subset: "not_songbirds"
 
  #normalization: None
  transforms:
    - name: matchres
      ignore: true
      target_size: [64, 64]
      
    - name: crop
      ignore: false
      p: 1
      ignore_band: ["bioclim", "ped"]
      center: true # disable randomness, crop around the image's center
      height: 64
      width: 64
    - name: resize
      ignore: false
      size: [256,256]
    - name: hflip
      ignore: "val"
      p: 0.5
    - name: vflip
      ignore: "val"
      p: 0.5
    - name: normalize
      ignore: false
      maxchan: false
      subset: ["sat"]
      custom: [[894.6719, 932.5726,693.2768, 2817.9849],[883.9763,747.6857,749.3098, 1342.6334]]
      #ImageNet values 
      #[[0.485, 0.456, 0.406],[0.229, 0.224, 0.225]]
      #Mean-std computed on training set
      #[[894.6719, 932.5726,693.2768], [883.9763,747.6857,749.3098]]
      #[894.6719, 932.5726,693.2768, 2817.9849], [883.9763,747.6857,749.3098, 1342.6334]
    - name: normalize
      ignore: true
      maxchan: false
      subset: ["bioclim"]
      custom: [*bioclim_means, *bioclim_std]
    - name: normalize
      ignore: true
      maxchan: false
      subset: ["ped"]
      custom: [*ped_means, *ped_std]
    - name: randomnoise
      ignore: True #false
      std: 0.01
      max_noise: 0.05
      
  total_species: 684
  

